# Generated by Django 4.0.1 on 2022-03-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_products_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='imagepath',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
